name: 'Approval Gate Checker Terraform Test'
description: 'A simple approval gate to approve/deny a Terraform Apply from running or not'
inputs:
  action:  # id of input
    description: 'Terraform action to take'
    required: true
    default: 'Plan'
  environment:
    description: 'Which environment to target'
    required: true
    default: 'Dev'
  current-branch:
    description: 'name of the current branch'
    required: true
  main-branch:
    description: 'name of the main/master branch'
    required: true

outputs:
  outcome: # id of output
    description: 'Outcome of the approval gate'

runs:
  using: 'node20'
  main: 'index.js'