name: Custom docker job run

on:
    workflow_dispatch:
        inputs:
            name:
                type: string
                description: name of who to greet

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        name: A job to say hello
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Hello world action step
              id: hello
              uses: ./
              with:
                who-to-greet: ${{ inputs.name }}
            
            
            - name: get the output time
              run: echo "The time was ${{ steps.hello.outputs.time }}"